### ISSUE TITLE
visitorLifetimeValue is "0" on guest checkout and new customer transaction

### ISSUE THREAD

**Issue by phildpearce** [CVM/Magento_GoogleTagManager#12]
visitorLifetimeValue is "0" on new customer transactions (e.g. visitorExistingCustomer=No).

If it`s a new customer then visitorLifetimeValue should be the value of the transaction.

e.g. if visitorExistingCustomer=No THEN visitorLifetimeValue = dataLayer.transactionTotal

If you generate a custom report with customDimension_visitorExistingCustomer and averageOf(customMetrics_visitorLifetimeValue) you will see the problem.

Also, custom report with customDimension_visitorId and averageOf(customMetrics_visitorLifetimeValue) also highlights this.

Thanks 

Phil.

**Comment by phildpearce** [comment]
Here is another example...

For new customers
1. Login/Guess checkout  with userID_001: £0 (revenue) and £0 (LTCV)
Order1 with userID_001: £200 (revenue)  and £200 (visitorLifeTimeValueMetrics) ... Thus... nonCumulative_LTCV needs to be £200
2. Order2 with userID_001: £100 (revenue) and £100 (visitorLifeTimeValueMetrics) ... Thus... nonCumulative_LTCV needs to be £300 (not a GA calculation of £400)
3. Order2 with userID_001: £100 (revenue) and £100 (visitorLifeTimeValueMetrics) ... Thus... nonCumulative_LTCV needs to be £400 (not a GA calculation of £500)

For existing customers
1. Login  with userID_001: £0 (revenue) and £9,900 (Cumulative_LTCV) ... on login (if no LTCV cookie exists)
2. Order1 with userID_001: £100 (revenue) and £100 (visitorLifeTimeValueMetrics) ... Thus... Cumulative_LTCV metric would be £1,000
3. Order2 with userID_001: £100 (revenue) and £100 (visitorLifeTimeValueMetrics) ... Thus... Cumulative_LTCV metric would be £1,100
4. Order2 with userID_001: £100 (revenue) and £100 (visitorLifeTimeValueMetrics) ... Thus... Cumulative_LTCV metric would be £1,100

**Comment by CVM** [comment]
This is a bug. Will add to roadmap.

**Comment by phildpearce** [comment]
Thanks :) 

When will this be pushed to MagentoConnect?

**Comment by CVM** [comment]
Not entirely sure yet. The process of packaging things up and submitting to Magento Connect is a bit time consuming. At the very least, I'd like to sort out issue #14 first before updating the release.
