### ISSUE TITLE
Analytics goal funnel

### ISSUE THREAD

**Issue by juggernaught** [CVM/Magento_GoogleTagManager#6]
Is there anything special that needs to be done to get the goal funnel to work in google analytics?

I previously had Foomans Analytics Plus installed and this worked on there.

**Comment by CVM** [comment]
I've not used Foomans Analytics Plus, but I would guess that the extension adds GA code to the checkout process to track each individual step as you move through the accordion (essentially pushing a pageview at each step).

With the current version of the extension this is not supported, though supporting this is on the radar for a future release (see discussion in issue #14). Note that when this is released, upgrading would not make the funnel work automatically, but would instead provide GTM events that could be used to trigger the desired GA events / pageviews to get the goal funnel working.
