### ISSUE TITLE
transactionAffiliation - change to use dataLayer.transactionPromoCode value instead

### ISSUE THREAD

**Issue by phildpearce** [CVM/Magento_GoogleTagManager#9]
Using the store name within transactionAffiliation is not helpful for analysis.

"Affiliation" should be used for "Affiliate PromoCodes".

Please change to dataLayer.transactionPromoCode and hide the setting text box in the magento interface.

Many Thanks

Phil.

**Comment by CVM** [comment]
Google's description of this field is:

_"The store or affiliation from which this transaction occurred (e.g. Acme Clothing)."_

So, the store name can be an appropriate value. Affiliation will be an interesting thing that can differ from business to business. This is why transactionAffiliation is provided simply as a free text input, configurable per store view. While you might want to use promocodes, other users would have other ideas for how they want it used.

Long term, the plan is to allow other extensions to push into the dataLayer for this extension, thereby allowing such business logic to be introduced. But in the short term, delving into utilising the field for customer-specific needs is out of scope.

**Comment by phildpearce** [comment]
Understood, but from an analysis point of view... it is more useful to see which AFFILIATE promo codes trigger a sale rather than "My Magento Store" - which is not very helpful. They already know the transaction is on their Magento Store ;)

I know can add this as a session level CustomDimension, but it is easier for the client if they can use the native report metrics, such as transactionAffiliation.

I suggest changing the default value to  dataLayer.transactionPromoCode , with the option to override via Magento setting to "My Magento Store".

Thanks
